# component url_path
# \uB9E4\uB274\uC5BC \uAD00\uB9AC
cm_mnl.url-path=/ma/sys/mnl/

# \uC77C\uC815\uAD00\uB9AC
cm_schd.url-path=/ma/usersupport/schedule/

# \uBC95\uC815\uB3D9\uCF54\uB4DC
cm_regCd.folder-path=/ma/sys/dm/regCd/

# \uD55C\uAE00(hwp)
cm_hwp.folder-path=/ma/us/hwp/

# \uC6A9\uC5B4\uC0AC\uC804
cm_term.url-path=/ma/us/std/term/
cm_dmn.url-path=/ma/us/std/dmn/
cm_wrd.url-path=/ma/us/std/wrd/

# DB\uD488\uC9C8
cm_dbData.url-path=/ma/us/dbQlt/dbData/
cm_tblDgns.url-path=/ma/us/dbQlt/tblDgns/
cm_termDgns.url-path=/ma/us/dbQlt/termDgns/

# ITSM root \uACBD\uB85C
cm_itsm.url-path=/itsm/

#\uC124\uBB38\uC870\uC0AC
cm_srvy.ma-url-path=/ma/us/srvy/
cm_srvy.ft-url-path=/ft/community/survey/